### ISSUE TITLE
open ~/talon -> bin -> update 

### ISSUE THREAD

**Issue by tararoys** [talonvoice/talon#114] opened 2020-06-10 17:21 UTC
On Windows 10, when opening talon from the menu,  and selecting Scripting -> open ~/talong

![image](https://user-images.githubusercontent.com/1163925/84298204-56ab8b80-ab14-11ea-9e86-207085d6ad7f.png)

Clicking on the Bin folder, 

![Talon Bin Shortcut](https://user-images.githubusercontent.com/1163925/84298350-9a05fa00-ab14-11ea-8d95-cb85824618b8.png)

And attempting to run Update, 

The following Error Message occurs:  

'""\python.exe' is not recognized as an internal or external command,
operable program or batch file.
Press any key to continue . . .

![Talon Update error message](https://user-images.githubusercontent.com/1163925/84298106-354a9f80-ab14-11ea-934b-ff47079a2462.png)

Note:  in chat it was asked what was inside the python file and the resource file in the directory.  

Both of those files contain one line.  They contain the following line: 

`C:\Program Files\Talon`

**Comment by lunixbochs** [comment] 2020-11-02 17:39
Duplicate of #113, and the new menu based updater doesn't use this process anymore.

**Closed as completed by lunixbochs** 2020-11-02 17:39 UTC
Labels: bug
