### ISSUE TITLE
[linux] ui.active_window().rect incorrect xpos/ypos

### ISSUE THREAD

**Issue by splondike** [talonvoice/talon#285] opened 2021-04-10 05:12 UTC
Under both GNOME3 (Xorg) and i3 the u.active_window().rect does not always give the correct x and y coordinates of the window. The width and height seem to be always correct.

The issue is particularly pronounced under GNOME3 where they appear to never be right if the window is floating (not maximised). Under i3 they are sometimes right. This affects both the public stable version (v0.1.5) and the latest beta (v0.1.5-51-g3121).

The following script demonstrates the issue. Make sure you have xdotool installed and then run Talon under GNOME3. A red box should be drawn around Talon's interpretation of the active window (updated every 3 seconds). The log contains a comparison with xdotool.

```python
import subprocess
from talon import cron, ui, canvas
from talon.types import Rect


def find_active_window_rect_xdotool():
    active_window_id = subprocess.run(
        ["xdotool", "getactivewindow"],
        capture_output=True,
        check=True
    ).stdout.strip()
    active_window_geom = subprocess.run(
        ["xdotool", "getwindowgeometry", "--shell", active_window_id],
        capture_output=True,
        check=True
    ).stdout
    val_map = {
        key.decode("utf8"): int(val)
        for line in active_window_geom.splitlines()
        for key, val in (line.split(b"="),)
    }

    return Rect(
        val_map["X"],
        val_map["Y"],
        val_map["WIDTH"],
        val_map["HEIGHT"],
    )

def _dump_info():
    global can, talon_rect, xdotool_rect
    talon_rect = ui.active_window().rect
    xdotool_rect = find_active_window_rect_xdotool()
    equal = "OK" if talon_rect == xdotool_rect else "NO"

    print(f"Active rect: {equal} t={talon_rect}, x={xdotool_rect}")
    can.freeze()  # Trigger redraw

def _draw(canvas):
    paint = canvas.paint
    paint.color = 'ff0000ff'
    paint.style = paint.Style.STROKE
    rect = talon_rect
    if rect is not None:
        canvas.draw_rect(rect)

talon_rect = None
xdotool_rect = None
cron.interval("3s", _dump_info)

can = canvas.Canvas.from_screen(ui.screens()[0])
can.register("draw", _draw)
can.freeze()
can.show()
```

**Comment by lunixbochs** [comment] 2021-04-10 05:34
Does your wm issue events when windows resize?

**Comment by splondike** [comment] 2021-04-11 01:27
I used `xev -root` to check this on i3 and GNOME3. It does appear that `ConfigureNotify` events are issued when moving or resising windows. Under GNOME3 they have the same x/y position and width/height as xdotool reports. Under i3 the values are a few pixels off the xdotool ones.

**Comment by lunixbochs** [comment] 2021-06-18 19:42
I think this is fixed now in 0.1.5-393, let me know if I messed it up

**Comment by splondike** [comment] 2021-06-19 08:51
We worked through the remaining problems with this today, and it's now working at least as well as xdotool under i3 and GNOME to the best of my testing with the as yet unreleased update.

The only remaining related issue is that GTK application that draw their own titlebar and drop shadows (e.g. gnome-terminal) have some extra padding which makes Talon (and xdotool) show the window rect as being wider than the actual 'content' (red border in screenshot below is what Talon/xdotool think the window geometry is).

![extra-padding](https://user-images.githubusercontent.com/113718/122636863-d825f880-d12e-11eb-8c09-709835f2e2cc.jpg) 

These GTK applications use an extra xwindows property (_GTK_FRAME_EXTENTS) to indicate how much of this extra padding there is. This property apparently isn't standardized however and this means it isn't supported by KDE either: https://www.reddit.com/r/kde/comments/c7i5zr/kwin_with_gtk_frame_extents_support_sick/

**Comment by lunixbochs** [comment] 2021-07-24 05:40
Looks like I should handle _GTK_FRAME_EXTENTS and also need to clip the ui.screens() visible_rect using `_NET_WORKAREA`

**Comment by lunixbochs** [comment] 2021-09-21 22:41
Just implemented GTK_FRAME_EXTENTS in the beta. For _NET_WORKAREA, I'm waiting on someone to post `xprop -root` from a multimonitor gnome system as well as their screen resolutions

**Comment by lunixbochs** [comment] 2021-10-26 15:52
workarea doesn't appear to be standard enough, I'm just going to drop that for now unless someone makes a formal request

**Comment by rntz** [comment] 2021-11-22 02:09
I'm not sure that GTK_FRAME_EXTENTS handling has been implemented correctly, on the following basis: if I run this function multiple times with a terminal window selected, the window gets narrower and narrower, even though this shouldn't be affecting its width. It also doesn't maximize to the full height of the screen.

```
    def snap_tall():
        """Maximizes the height of the current window."""
        w = ui.active_window()
        area = w.screen.visible_rect
        r = w.rect
        r.y = area.y
        r.height = area.height
        w.rect = r
```

Ubuntu 21.10, talon v0.2.0-171

![Screenshot from 2021-11-22 02-02-11](https://user-images.githubusercontent.com/16143/142790648-de50aff2-41d5-4279-a8ac-35b2dc4b9006.png)
![Screenshot from 2021-11-22 02-02-38](https://user-images.githubusercontent.com/16143/142790653-f28243f2-ded8-47d5-b308-15b6f8cb54fc.png)
![Screenshot from 2021-11-22 02-03-35](https://user-images.githubusercontent.com/16143/142790662-b16b20ff-d120-4eba-b245-3240b9dece46.png)

**Comment by lunixbochs** [comment] 2021-11-22 02:42
I think reading the frame is working as intended, but writing it needs to account for the extents, as the target app must expect you to include the extents when moving the window

**Comment by rntz** [comment] 2021-11-24 19:26
Should this issue be reopened then, or a new one created?

**Comment by lunixbochs** [comment] 2021-11-24 19:38
It's sort of a new feature but I'll just reopen this

**Comment by lunixbochs** [comment] 2021-11-30 07:27
I now account for the gtk frame extents in 0.2.0-206 when setting the rect

**Closed as completed by lunixbochs** 2021-11-30 07:27 UTC
Labels: bug, linux
