### ISSUE TITLE
Bluetooth mic requires Talon restart

### ISSUE THREAD

**Issue by Jacob1234098** [talonvoice/talon#253] opened 2021-02-25 18:34 UTC
I have switched to using a bluetooth microphone which works great except every time I turn off the mic (which disconnects the bluetooth) then restart the mic and reconnect it to bluetooth, I have to restart Talon for voice control to work. Talon acts like it is using the system default which is the bluetooth mic but it doesn’t work without a restart. talon v 0.1.4

**Comment by Jacob1234098** [comment] 2021-02-25 18:35
I am using a BlueParrott C400-XT mic

**Comment by lunixbochs** [comment] 2021-06-11 21:08
Closing as duplicate of #292

**Closed as completed by lunixbochs** 2021-06-11 21:08 UTC
Labels: bug, mac
