### ISSUE TITLE
Talon uses wrong keyboard layout in first detection after pressing physical keys

### ISSUE THREAD

**Issue by polygon** [talonvoice/talon#532] opened 2022-10-24 09:25 UTC
I'm using a German keyboard and I've noticed some strange behavior when mixing talon with physically typing on the keyboard. It seems as if the first detection after physically pressing a key is using the wrong keyboard layout. This is a bit difficult to explain so I've attached a video showcasing the issue.

I'm running Talon 0.3.1 on Linux. Please let me know if I can do anything to help further analyze the issue.

https://user-images.githubusercontent.com/51489/197493419-aaca927e-2ccd-49ba-a2c8-8f847ec3f835.mp4

**Comment by lunixbochs** [comment] 2023-01-19 19:06
does this happen in apps besides vscode?

**Comment by weltoph** [comment] 2023-02-07 16:11
After having asked  the same question on slack I was pointed to #540 (thanks again). As suggested there one can use `setxkbmap` to set a keyboard layout. Doing so solved the issue for me. I hope it helps you too!

**Comment by lunixbochs** [comment] 2023-05-26 04:10
this appear to be a duplicate of #540

**Closed as not planned by lunixbochs** 2023-05-26 04:10 UTC
Labels: needs-triage
