### ISSUE TITLE
Format string type checking errors in talonscript don't tell you where the problem is

### ISSUE THREAD

**Issue by jgarvin** [talonvoice/talon#118] opened 2020-10-23 21:11 UTC
If you register a function with `talon.cron` that has a mistake in it, the stack trace doesn't help you debug it because the only entries are from talon:

```
2020-10-23 16:03:58 ERROR failed to type check script
   41:       lib/python3.7/threading.py:890| 
   40:       lib/python3.7/threading.py:926| 
   39:       lib/python3.7/thre ading.py:870| 
   38:                    talon/cron.py:112| 
   37: ------------------------------------# cron thread
   36:                    talon/cron.py:77 | 
   35:          talon/scripting/rctx.py:200| 
   34: ------------------------------------# 'cron' main:<lambda>()
   33:                     talon/vad.py:16 | 
   32:             talon/engines/w2l.py:745| 
   31:      talon/scripting/dispatch.py:98 | 
   30:      talon/scripting/dispatch.py:133| 
   29:      talon/scripting/dispatch.py:124| 
   28:          talon/scripting/rctx.py:200| 
   27: ------------------------------------# 'phrase' user.engines:_redispatch()
   26: talon/scripting/speech_system.py:42 | 
   25:      talon/scripting/dispatch.py:98 | 
   24:      talon/scripting/dispatch.py:133| 
   23:      talon/scripting/dispatch.py:124| 
   22:          talon/scripting/rctx.py:200| 
   21: ------------------------------------# 'phrase' user.engines:engine_event()
   20: talon/scripting/speech_system.py:305| 
   19:       talon/scripting/actions.py:56 | 
   18:         talon/scripting/types.py:313| 
   17:          talon/scripting/core.py:84 | 
   16:       talon/scripting/actions.py:56 | 
   15:         talon/scripting/types.py:313| 
   14:          talon/scripting/core.py:106| 
   13:       talon/scripting/actions.py:56 | 
   12:         talon/scripting/types.py:313| 
   11:          talon/scripting/core.py:121| 
   10:       talon/scripting/actions.py:56 | 
    9:         talon/scripting/types.py:313| 
    8:          talon/scripting/core.py:142| 
    7:  talon/scripting/talon_script.py:513| 
    6: ------------------------------------# stack splice
    5:  talon/scripting/talon_script.py:511| 
    4:  talon/scripting/talon_script.py:487| 
    3:  talon/scripting/talon_script.py:242| 
    2:  talon/scripting/talon_script.py:178| 
    1:                         <string>:1  | 
NameError: name 'k' is not defined
```

I think this is because the function is being saved as a callback. However, I believe the python `inspect` module lets you extract source code locations from function objects, so should be possible to give the user a more helpful error.

Edit: issue is actually due to this code in talonscript:

```
desk <user.number_key>:
    k = user.unmap_number(number_key)
    key("ctrl-alt-{k}")
```

Because the type checking doesn't understand format strings. The error could be improved to let you know that the problem is in talon script instead of python and which talon script file.

**Comment by lunixbochs** [comment] 2020-11-02 17:26
Closing as duplicate of #144

**Closed as completed by lunixbochs** 2020-11-02 17:26 UTC

**Comment by lunixbochs** [comment] 2020-11-03 04:35
Fixed in next beta:
```
talon.scripting.talon_script.TalonScriptError: 
 in script at /Users/aegis/.talon/user/knausj_talon/misc/keys.talon:13:
   x = 1
 > print('hello {y} etc')
NameError: y
```
