### ISSUE TITLE
Title doesn't update for Emacs on MacOS

### ISSUE THREAD

**Issue by wenkokke** [talonvoice/talon#349] opened 2021-07-12 11:12 UTC
Neither `ui.active_window().title` nor `actions.window.title()` is able to get the updated window title for Emacs on MacOS.

I am running Emacs version 27.2 on MacOS. The bug was independently reproduced:
https://talonvoice.slack.com/archives/C9MHQ4AGP/p1625933436168200

**Comment by wenkokke** [comment] 2021-07-12 11:13
Temporary workaround on MacOS available here:
https://talonvoice.slack.com/archives/C9MHQ4AGP/p1625935709170100?thread_ts=1625933436.168200&cid=C9MHQ4AGP

**Comment by lunixbochs** [comment] 2023-07-11 08:38
was this fixed alongside #502?

**Comment by wenkokke** [comment] 2023-07-11 11:12
I can't confirm this, since I moved away from emacs.

**Comment by rntz** [comment] 2023-07-12 11:49
As of talon-0.3.1-673-gcf9d I cannot reproduce this. However, I never explicitly tried to reproduce this on prior versions of Talon, and I'm using a different emacs version (28.2).

**Comment by lunixbochs** [comment] 2023-07-13 06:44
alright, closing as it's probably fixed. we can reopen if someone finds a new repro in emacs.

**Closed as completed by lunixbochs** 2023-07-13 06:44 UTC
Labels: bug, mac
