### ISSUE TITLE
When application starts after talon, the scope is wrong

### ISSUE THREAD

**Issue by PetrKryslUCSD** [talonvoice/talon#613] opened 2023-05-05 00:38 UTC
On Windows 10: when an application is started at the point where Talon is already running, often the scope is that of the previously active window. Sometimes switching applications will correct the issue, sometimes one has to restart Talon for the scope to be correct.

**Comment by lunixbochs** [comment] 2023-05-05 00:53
I just fixed a bug related to this in beta 592, please confirm whether the issue appears after that version

**Comment by PetrKryslUCSD** [comment] 2023-05-05 15:04
Looks good! Many thanks. P

**Comment by PetrKryslUCSD** [comment] 2023-05-06 15:42
Spoke to soon. The error still persists.

**Comment by lunixbochs** [comment] 2023-05-06 19:10
does the new application show up in ui.apps() in the repl?
does the new window show up in ui.windows()?
is the right window active for the app, if you find the app in ui.apps() and check app.active_window?
is this related to specific apps each time, or if you launch a random app like notepad does it also have the issue?

**Comment by AndreasArvidsson** [comment] 2023-05-07 06:50
* yes
* yes
* no: `Window(None)` is the active window. app.windows shows the correct window as the first item though
* Seems to happen with different applications, but doesn't happen every time. If I restart Talon multiple times sometimes there is a problem and sometimes not. Notepad is one of the applications I've had problems with but also firefox for example.

beta 596
windows 11

**Comment by PetrKryslUCSD** [comment] 2023-05-07 19:13
Just happened again. 596, Win 11.
![image](https://user-images.githubusercontent.com/9855832/236697899-5ae743bd-68f0-405e-b4a4-d4c4f1ef141e.png)
The application is SublimeMerge.

**Comment by PetrKryslUCSD** [comment] 2023-05-07 19:14
Switching applications a few times and checking the scope again: now it is correct.

**Comment by dgrunwald** [comment] 2023-05-08 08:13
I frequently have this issue with a newly started windows terminal (the modern app; on Windows 10). Just had it again with 0.3.1-596-ge72c.
Switching focus to another app and back to Windows terminal is almost always sufficient as a workaround; though very rarely I had to restart talon (but the last time that happened was a couple versions ago).

**Comment by mirober** [comment] 2023-05-09 18:21
I've very occasionally run into the same thing but have never been able to find a reliable repro for it. One thing that seems to be able to trigger it is launching applications from the path bar of a file explorer window. This only triggers the bug sometimes though and usually only the first time after a restart. Just tried it on the latest beta and got this:

![image](https://github.com/talonvoice/talon/assets/42875462/38026ef9-fe8a-4b2d-a1a9-c04bb66cec96)

![image](https://github.com/talonvoice/talon/assets/42875462/57c002e3-4c7e-40c8-9fc3-daf0b7949871)

The imgui window is showing:
```
    gui.text(f"{ui.active_app()}")
    gui.text(f"{ui.active_app().exe}")
    gui.text(f"{ui.active_window().title}")
    gui.text(f"{GetForegroundWindow()}")
    gui.text(f"{GetWindowText(GetForegroundWindow())}")
    gui.text(f"{GetWindowText(ui.active_window().id)}")
```

This may be a separate issue to the OP.

**Comment by lunixbochs** [comment] 2023-05-10 05:13
try again on 597

**Comment by AndreasArvidsson** [comment] 2023-05-10 09:26
I've been trying to recreate the problem and can't anymore. That could mean that it's fixed or that it has just become more seldom since it was intermittent before, but so far so good!

**Comment by dgrunwald** [comment] 2023-05-11 10:27
I got the problem again on version 597, this time the variant where focus switching does not help.
I had to restart talon to get it to recognize the newly opened applications (VSCode, notepad, ...)

It was affecting all newly opened apps after the problem started occurring (probably when resuming from hibernation over night?), but not newly opened windows of already-running apps.

**Comment by mirober** [comment] 2023-05-11 16:59
repro'd mine on 597

**Comment by lunixbochs** [comment] 2023-05-11 17:09
after your repro, is there an error in your log? I found the cause for dgrunwald's and it was due to an exception

**Comment by mirober** [comment] 2023-05-11 17:24
Could a user level error in a `win_title` event handler cause this? There aren't any errors from talon itself

**Comment by lunixbochs** [comment] 2023-05-11 17:40
ping me on slack, you might have a different issue

**Comment by lunixbochs** [comment] 2023-05-11 19:06
no, win_title wouldn't cause this. fwiw there's a new update (599) for the general case

**Comment by PetrKryslUCSD** [comment] 2023-05-13 01:27
With 599 I haven't been able to reproduce yet. Fingers crossed...

**Comment by lunixbochs** [comment] 2023-05-13 21:00
closing this again, respond here if it reappears

**Closed as completed by lunixbochs** 2023-05-13 21:00 UTC
Labels: bug, windows

**Comment by PetrKryslUCSD** [comment] 2023-05-15 14:06
It happened again today.

**Comment by lunixbochs** [comment] 2023-05-15 15:59
@PetrKryslUCSD going to DM you on the slack, there are some extra troubleshooting steps required
