### ISSUE TITLE
Two or more levels of derivation not supported by type checking

### ISSUE THREAD

**Issue by pokey** [talonvoice/talon#533] opened 2022-11-02 14:03 UTC
If I indicate that an action parameter has a particular type, Talon will throw an error if it receives an instance of a type that is not a direct derived type of the expected type.  For example:

### `testing.py`

```python
from talon import Module

mod = Module()


class Aaa:
    pass


class Bbb(Aaa):
    pass


class Ccc(Bbb):
    pass


@mod.capture(rule="testing testing")
def test_derived(m) -> Ccc:
    return Ccc()


@mod.action_class
class Actions:
    def test_action_derived(arg: Aaa):
        """This is an action"""
        print("Testing")
```

### `testing.talon`

```talon
<user.test_derived>: user.test_action_derived(test_derived)
```

## Error

Saying `"testing testing"` will result in the following error:

```
2022-11-02 13:58:46 ERROR TalonScript TypeError in: /Users/pokey/.talon/user/pokey_talon/apps/vscode/testing.talon:1
2022-11-02 13:58:46 ERROR Line 1: user.test_action_derived(arg: user.pokey_talon.apps.vscode.testing.Aaa)
2022-11-02 13:58:46 ERROR Line 1:   parameter 1 (arg) expects type <class 'user.pokey_talon.apps.vscode.testing.Aaa'>, got <class 'user.pokey_talon.apps.vscode.testing.Ccc'>
```

Note that the action still runs, it just results in a spurious error message in the log

Changing the expected type of `arg` to `Bbb` results in no error, as the received argument is then a direct derived type

**Comment by lunixbochs** [comment] 2023-01-19 20:06
duplicate of https://github.com/talonvoice/talon/issues/415

**Closed as completed by lunixbochs** 2023-01-19 20:06 UTC
Labels: needs-triage
