### ISSUE TITLE
[linux] talon-rust -  cron interval RuntimeError: dictionary changed size during iteration

### ISSUE THREAD

**Issue by fidgetingbits** [talonvoice/talon#600] opened 2023-03-29 02:09 UTC
Just filing here so I don't forget, although I mentioned it to you on slack as well. I get this error on every startup, which I didn't get on the non-rust beta. 

```
2023-03-29 10:03:13 ERROR cron interval error <function _rescan at 0x7fc6de707820>
    8: lib/python3.9/threading.py:937* # cron thread
    7: lib/python3.9/threading.py:980* 
    6: lib/python3.9/threading.py:917* 
    5:              talon/cron.py:153| 
    4:    talon/scripting/rctx.py:235| # 'cron' main:Cron.interval.<locals>.call()
    3:              talon/cron.py:181| # [stack splice]
    2:                talon/fs.py:61 | 
    1:     talon/lib/fs_shadow.py:193| 
RuntimeError: dictionary changed size during iteration
```

I also get it periodically in my talon log after startup is finished, although it doesn't seem to have any adverse effect anywhere. I don't mind the spam in general, most confusing is it telling me I have in error at startup, which is normally due to errors in my own talon scripts.

**Comment by phillco** [comment] 2023-03-29 02:11
I think I've seen this too on startup, I just forgot to file it.

**Comment by lunixbochs** [comment] 2023-03-29 02:19
duplicate of #560

**Closed as not planned by lunixbochs** 2023-03-29 02:19 UTC
