### ISSUE TITLE
Talon-Rust: Windows UAC disables eye tracker

### ISSUE THREAD

**Issue by AndreasArvidsson** [talonvoice/talon#568] opened 2023-03-06 08:25 UTC
Went to install geekbench and when the UAC prompt came up my eye tracker died. This works fine on Talon-qt.
```
2023-03-06 09:16:49 ERROR cron interval error <bound method BaseControlMouse.tick of <talon.plugins.eye_mouse_2.ControlMouse2 object at 0x0000000004E8D970>>
   10:                 threading.py:937* # cron thread
    9:                 threading.py:980*
    8:                 threading.py:917*
    7:                talon\cron.py:148|
    6:      talon\scripting\rctx.py:235| # 'cron' tracking:Cron.interval.<locals>.call()
    5:                talon\cron.py:176| # [stack splice]
    4:                contextlib.py:79 |
    3: talon\plugins\eye_mouse_2.py:138|
    2: talon\plugins\eye_mouse_2.py:404|
    1:        talon\windows\ctrl.py:141|
pywintypes.error: (0, 'SetCursorPos', 'No error message is available')
```

**Comment by lunixbochs** [comment] 2023-03-06 08:26
you double filed this, duplicate of #567

**Closed as not planned by lunixbochs** 2023-03-06 08:26 UTC

**Comment by AndreasArvidsson** [comment] 2023-03-06 08:30
Thanks. I appear to have slow downs and probably hit the button twice.
