### ISSUE TITLE
Smooth scrolling on Linux does not work in Qt5 apps

### ISSUE THREAD

**Issue by RichardHladik** [talonvoice/talon#360] opened 2021-07-25 22:28 UTC
Currently, smooth scrolling (i.e. with `by_lines=False`) seems to work on all but Qt5 applications on my Arch Linux system. What I tried (mostly after being told to on Slack):

* Using `by_lines=True`. This works.
* Scrolling by a ridiculously large amount (`y=1000`), or repeatedly scrolling by a sensible amount (`y=10`). Neither works.
* Making the apps that support it use a different framework than Qt5. This worked in all cases, examples below.

Apps I tried (all of them affected, all of them using Qt5 AFAIK):
* neovim-qt
* vlc (but works when run as `vlc -I skins2`)
* libreoffice (but only as `SAL_USE_VCLPLUGIN=qt5 libreoffice`, works fine with `SAL_USE_VCLPLUGIN=gtk libreoffice`)
* telegram-desktop
* okular, kdenlive, and most likely other KDE apps

My current Qt version is 5.15.2. As this seems to affect exclusively Qt applications, I'm curious if this isn't a Qt5 bug after all.

Incidentally, `insert("🤦")`-ing emojis also fails for precisely these apps on my system (except for neovim-qt, which works for some reason), but that is a thing for another issue/investigation.

**Comment by lunixbochs** [comment] 2021-07-26 21:33
can you compare, using xev, the scroll events simulated by talon, vs smooth scroll events from another device?

**Comment by RichardHladik** [comment] 2021-07-26 22:16
I tried to, see the two attached logs ([real.log](https://github.com/talonvoice/talon/files/6881498/real.log), [talon.log](https://github.com/talonvoice/talon/files/6881499/talon.log)) – I've aligned their line numbers for the first 300 lines or so, then it starts to desync. BTW apparently, `xev` isn't XInput2-capable, so `xinput text-xi2` is the new xev.

I don't see anything obviously amiss. My three observations:

* With the touchpad, some events are doubled, but I guess that's just because they are reported once for the actual touchpad and once for the "root" pointer device.
* Talon always sends all 4 valuators in the RawMotion while the touchpad only sends the nonzero ones (but in the subsequent Motion event they already reduced to just the nonzeros)
* The touchpad always sends this `EVENT type 1 (DeviceChanged)`, even when I alternate between the touchpad scrolling and talon scrolling, while talon sends no such thing (can the "root" device even send such events? IDK). Maybe Qt5 populates the device info when no such event arrives with some dumb defaults? (e.g. I can see some increment values in the touchpad log, lines 108 and 113). Just wild guesses, I have no idea what I'm doing.

**Comment by lunixbochs** [comment] 2021-07-26 22:35
An awesome thing you could do is find a way to debug this inside Qt, maybe track down where smooth scroll events are handled in their X11 backend.

**Comment by RichardHladik** [comment] 2021-10-03 10:41
I still need to find the time to debug this. In the meantime, here's my workaround for anyone interested:

https://github.com/RichardHladik/knausj_talon/commit/dc67801a59efc577f9010a2056501f5570bea14d

(basically, just turn off smooth scrolling on per-app basis)

**Comment by lunixbochs** [comment] 2022-05-02 06:34
is this somehow related to https://github.com/talonvoice/talon/issues/330?

**Comment by RichardHladik** [comment] 2022-05-02 20:53
Seems like it, or at least I can repro the behaviour:

* Smooth scrolling in apps where it normalls works stops working when I frantically move the mouse pointer at the same time (well, doesn't fully stop, some events still seem to get through, but it scrolls way slower).

* `imwheel -b 45` "fixes" the issue for Qt apps (probably by taking smooth scrolling events and emitting wheel scrolling events), but also introduces double scrolling for apps where smooth scrolling works. The effect is that the two scrolling types get summed up and a result is a "rolling-egg" kind of scrolling.

**Comment by lunixbochs** [comment] 2023-01-19 20:19
closing as duplicate of #330

**Closed as completed by lunixbochs** 2023-01-19 20:19 UTC
Labels: bug
