### ISSUE TITLE
Feature idea: Recognize speaker voice

### ISSUE THREAD

**Issue by maxbruening** [talonvoice/talon#612] opened 2023-05-03 07:50 UTC
I was thinking it would be nice if talon could single out my voice. Initially, this could be done just by voice pitch. A scenario in which this would be useful is for example two persons working together in a room, one with a really high voice, one with a really low voice.

**Comment by lunixbochs** [comment] 2023-05-26 04:33
duplicate of https://github.com/talonvoice/talon/issues/136

**Closed as not planned by lunixbochs** 2023-05-26 04:33 UTC
Labels: enhancement
